name: Publish test.txt with differential updates (uBO + AdGuard)

on:
  push:
    branches: [ master ]
    paths:
      - 'test.txt'

jobs:
  publish-test:
    runs-on: ubuntu-latest

    env:
      GH_EMAIL: "actions@users.noreply.github.com"
      GH_NAME:  "github-actions[bot]"
      SITE_DIR: "site"         # gh-pages worktree
      PATCH_DIR: "patches"     # patch-kansio gh-pagesissa
      DIFF_RESOLUTION: "m"     # m = minutes (nimiin)
      DIFF_EXPIRES_MIN: "300"  # 5 h minuutteina -> ...-300.patch (nimen osa)
      LIST_FILE: "test.txt"    # vain tämä tiedosto

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Prepare gh-pages worktree
        run: |
          set -e
          git fetch --depth=1 origin gh-pages:gh-pages || true
          git worktree add "${SITE_DIR}" gh-pages || git checkout gh-pages
          mkdir -p "${SITE_DIR}/${PATCH_DIR}"

      - name: Compute timestamps (RFC 2822, Europe/Helsinki)
        id: ts
        run: |
          RFC2822=$(TZ=Europe/Helsinki date -R)
          EPOCH_MIN=$(( $(date -u +%s) / 60 ))
          echo "rfc2822=${RFC2822}"     >> $GITHUB_OUTPUT
          echo "epoch_min=${EPOCH_MIN}" >> $GITHUB_OUTPUT

      - name: Build gh-pages version + BUNDLE RCS patch for uBO
        run: |
          set -euo pipefail

          SRC="${LIST_FILE}"                      # master-versio (sis. %timestamp%)
          DEST="${SITE_DIR}/${LIST_FILE}"         # gh-pages-kohde

          # edellinen julkaistu versio (jos ei ole, tyhjä tiedosto)
          if [[ -f "${DEST}" ]]; then
            cp "${DEST}" prev.txt
          else
            touch prev.txt
          fi

          # kopioi uusin master-versio ja korvaa Last modified RFC 2822 -ajalla
          cp "${SRC}" new_raw.txt
          if grep -qE '^! +Last modified:' new_raw.txt; then
            sed -E "s/^! +Last modified:.*$/! Last modified: ${RFC2822}/" new_raw.txt > new.txt
          else
            if grep -qE '^! +Description:' new_raw.txt; then
              awk -v lm="! Last modified: ${RFC2822}" '
                {print}
                /^! Description:/ && !done {print lm; done=1}
              ' new_raw.txt > new.txt
            elif grep -qE '^! +Title:' new_raw.txt; then
              awk -v lm="! Last modified: ${RFC2822}" '
                {print}
                /^! Title:/ && !done {print lm; done=1}
              ' new_raw.txt > new.txt
            else
              printf '! Last modified: %s\n' "${RFC2822}" > new.txt
              cat new_raw.txt >> new.txt
            fi
          fi

          # lisää/päivitä Diff-Expires (uBO:lle selkeästi tunneissa) — Expires-riviin ei kosketa
          if grep -qE '^! +Diff-Expires:' new.txt; then
            sed -i "s/^! \+Diff-Expires:.*/! Diff-Expires: 5 hours/" new.txt
          else
            awk -v d="! Diff-Expires: 5 hours" '
              {print}
              /^! Expires:/ && !done {print d; done=1}
            ' new.txt > new.tmp && mv new.tmp new.txt
          fi

          # Luo patchin nimi ja suhteellinen polku
          PATCH_NAME="test-${DIFF_RESOLUTION}-${{ steps.ts.outputs.epoch_min }}-${DIFF_EXPIRES_MIN}.patch"
          REL_PATCH_PATH="${PATCH_DIR}/${PATCH_NAME}"

          # päivitä/lisää Diff-Path suhteellisena + lohkonimi #test.txt (uBO bundle-valinta)
          if grep -qE '^! +Diff-Path:' new.txt; then
            sed -i "s#^! \+Diff-Path:.*#! Diff-Path: ${REL_PATCH_PATH}#test.txt#" new.txt
          else
            awk -v p="! Diff-Path: ${REL_PATCH_PATH}#test.txt" '
              {print}
              /^! Diff-Expires:/ && !done {print p; done=1}
            ' new.txt > new.tmp && mv new.tmp new.txt
          fi

          # sanity check: Diff-Path vastaa juuri luotavaa patchia (+ lohkonimi)
          grep -qE "^! Diff-Path: ${REL_PATCH_PATH}#test.txt$" new.txt || { echo "ERROR: Diff-Path mismatch"; exit 1; }

          # Kirjoita uusi gh-pages versio
          mkdir -p "$(dirname "${DEST}")"
          cp new.txt "${DEST}"

          # RCS-diff (old -> new)
          diff -n prev.txt new.txt > raw.patch || true

          # Laske checksum (SHA1) uuden TIEDOSTON sisällöstä ja patch-rivien lukumäärä
          SHA1_FULL=$(sha1sum new.txt | awk '{print $1}')
          LINES=$(wc -l < raw.patch | tr -d ' ')

          # Kirjoita BUNDLE-patch uBO:lle: header + RCS-runko
          {
            echo "diff name:test.txt checksum:${SHA1_FULL} lines:${LINES}"
            cat raw.patch
          } > "${SITE_DIR}/${REL_PATCH_PATH}"
        env:
          RFC2822: ${{ steps.ts.outputs.rfc2822 }}

      - name: Commit & push gh-pages
        working-directory: ${{ env.SITE_DIR }}
        run: |
          set -e
          git config user.email "${GH_EMAIL}"
          git config user.name  "${GH_NAME}"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update modified filter lists"
            git push origin HEAD:gh-pages
          else
            echo "No changes to publish."
          fi
