name: Publish test lists (uBO and AdGuard)

on:
  push:
    branches: [ master ]
    paths:
      - "test.txt"
      - "test_ubo_extras.txt"

permissions:
  contents: write

concurrency:
  group: publish-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_EMAIL: actions@users.noreply.github.com
      GH_NAME: github-actions[bot]

      SITE_DIR: site
      PATCH_DIR: patches

      SRC_MAIN: test.txt
      SRC_EXTRA: test_ubo_extras.txt

      OUT_UBO_MAIN: test.txt
      OUT_AG_MAIN: testAG.txt
      OUT_UBO_EXTRA: test_ubo_extras.txt
      OUT_AG_EXTRA: test_ubo_extrasAG.txt

      BASES_MAIN: bases/test-main
      BASES_EXTRA: bases/test-extra

      RETENTION_DAYS: "30"
      DIFF_EXPIRES_HUMAN: "5 hours"
      DIFF_EXPIRES_MIN: "300"

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Detect changed files and enforce extras->main
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          CHANGED="$(git show --name-only --pretty="" "${GITHUB_SHA}" || true)"
          echo "Changed files:"
          echo "${CHANGED}"

          NEED_MAIN=0
          NEED_EXTRA=0
          echo "${CHANGED}" | grep -E '(^|/)test\.txt$'            >/dev/null && NEED_MAIN=1  || true
          echo "${CHANGED}" | grep -E '(^|/)test_ubo_extras\.txt$' >/dev/null && NEED_EXTRA=1 || true

          if [[ "${NEED_MAIN}" == "0" && "${NEED_EXTRA}" == "0" ]]; then
            CHANGED_F="$(git diff --name-only HEAD~1..HEAD || true)"
            echo "Fallback last-commit diff:"
            echo "${CHANGED_F}"
            echo "${CHANGED_F}" | grep -E '(^|/)test\.txt$'            >/dev/null && NEED_MAIN=1  || true
            echo "${CHANGED_F}" | grep -E '(^|/)test_ubo_extras\.txt$' >/dev/null && NEED_EXTRA=1 || true
          fi

          if [[ "${NEED_EXTRA}" == "1" ]]; then NEED_MAIN=1; fi

          echo "NEED_MAIN=${NEED_MAIN}"   >> $GITHUB_ENV
          echo "NEED_EXTRA=${NEED_EXTRA}" >> $GITHUB_ENV
          echo "Resolved NEED_MAIN=$NEED_MAIN NEED_EXTRA=$NEED_EXTRA"

      - name: Prepare gh-pages worktree
        shell: bash
        run: |
          set -e
          git fetch --depth=1 origin gh-pages:gh-pages || true
          rm -rf "${SITE_DIR}" || true
          git worktree add "${SITE_DIR}" gh-pages
          mkdir -p "${SITE_DIR}/${PATCH_DIR}" "${SITE_DIR}/${BASES_MAIN}" "${SITE_DIR}/${BASES_EXTRA}"
          git -C "${SITE_DIR}" config user.email "${GH_EMAIL}"
          git -C "${SITE_DIR}" config user.name  "${GH_NAME}"

      - name: Compute timestamps
        id: ts
        shell: bash
        run: |
          RFC2822=$(TZ=Europe/Helsinki date -R)
          NOW_EPOCH=$(date -u +%s)
          EPOCH_MIN=$(( NOW_EPOCH / 60 ))
          echo "rfc2822=${RFC2822}"     >> $GITHUB_OUTPUT
          echo "now_epoch=${NOW_EPOCH}" >> $GITHUB_OUTPUT
          echo "epoch_min=${EPOCH_MIN}" >> $GITHUB_OUTPUT

      - name: Build headers (only needed)
        shell: bash
        env:
          RFC2822: ${{ steps.ts.outputs.rfc2822 }}
          DIFF_EXPIRES_HUMAN: ${{ env.DIFF_EXPIRES_HUMAN }}
          NEED_MAIN: ${{ env.NEED_MAIN }}
          NEED_EXTRA: ${{ env.NEED_EXTRA }}
        run: |
          set -euo pipefail
          build_headers () {
            local src="$1" dest="$2"
            if [[ -f "${src}" ]]; then cp "${src}" raw.txt; else : > raw.txt; fi
            awk -v lm="! Last modified: ${RFC2822}" '
              BEGIN{ done_lm=0 }
              {
                if ($0 ~ /^! +Last modified:/) { if (!done_lm) { print lm; done_lm=1 }; next }
                if ($0 ~ /^! +Diff-Path:/)     { next }
                print
              }
              END { if (!done_lm) print lm }
            ' raw.txt > t1.txt
            if grep -qE '^! +Diff-Expires:' t1.txt; then
              sed -E "s/^! +Diff-Expires:.*/! Diff-Expires: ${DIFF_EXPIRES_HUMAN}/" t1.txt > t2.txt
            else
              awk -v d="! Diff-Expires: ${DIFF_EXPIRES_HUMAN}" '
                BEGIN{ added=0 }
                { print; if ($0 ~ /^! +Expires:/ && !added) { print d; added=1 } }
                END { if (!added) print d }
              ' t1.txt > t2.txt
            fi
            cp t2.txt "${dest}"
          }

          if [[ "${NEED_MAIN}" == "1" ]]; then
            build_headers "${SRC_MAIN}"  "${SITE_DIR}/${OUT_UBO_MAIN}"
            build_headers "${SRC_MAIN}"  "${SITE_DIR}/${OUT_AG_MAIN}"
          fi
          if [[ "${NEED_EXTRA}" == "1" ]]; then
            build_headers "${SRC_EXTRA}" "${SITE_DIR}/${OUT_UBO_EXTRA}"
            build_headers "${SRC_EXTRA}" "${SITE_DIR}/${OUT_AG_EXTRA}"
          fi

      - name: Add Diff-Path
        shell: bash
        env:
          NEED_MAIN: ${{ env.NEED_MAIN }}
          NEED_EXTRA: ${{ env.NEED_EXTRA }}
          DIFF_EXPIRES_MIN: ${{ env.DIFF_EXPIRES_MIN }}
        run: |
          set -euo pipefail
          NOW_EPOCH=${{ steps.ts.outputs.now_epoch }}
          EPOCH_MIN=${{ steps.ts.outputs.epoch_min }}

          Y=$(date -u -d "@${NOW_EPOCH}" +%Y)
          Mo=$(date -u -d "@${NOW_EPOCH}" +%-m)
          D=$(date -u -d "@${NOW_EPOCH}" +%-d)
          H=$(date -u -d "@${NOW_EPOCH}" +%H)
          Mi=$(date -u -d "@${NOW_EPOCH}" +%M)
          MINS=$(( 10#${H}*60 + 10#${Mi} ))
          PATCH_UBO="${Y}.${Mo}.${D}.${MINS}.patch"
          REL_UBO="${PATCH_DIR}/${PATCH_UBO}"

          PATCH_AG_MAIN="testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
          REL_AG_MAIN="${PATCH_DIR}/${PATCH_AG_MAIN}"
          PATCH_AG_EXTRA="test_ubo_extrasAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
          REL_AG_EXTRA="${PATCH_DIR}/${PATCH_AG_EXTRA}"

          add_path () {
            local file="$1" rel="$2" frag="$3"
            local line="! Diff-Path: ${rel}#${frag}"
            grep -vE '^! +Diff-Path:' "$file" > tmp && mv tmp "$file"
            awk -v p="$line" '
              BEGIN{ins=0}
              { print; if ($0 ~ /^! +Diff-Expires:/ && ins==0) { print p; ins=1 } }
              END { if (ins==0) print p }
            ' "$file" > tmp && mv tmp "$file"
          }

          if [[ "${NEED_MAIN}" == "1" ]]; then
            add_path "${SITE_DIR}/${OUT_UBO_MAIN}"  "${REL_UBO}"     "test.txt"
            add_path "${SITE_DIR}/${OUT_AG_MAIN}"   "${REL_AG_MAIN}" "testAG.txt"
          fi
          if [[ "${NEED_EXTRA}" == "1" ]]; then
            add_path "${SITE_DIR}/${OUT_UBO_EXTRA}" "${REL_UBO}"      "test_ubo_extras.txt"
            add_path "${SITE_DIR}/${OUT_AG_EXTRA}"  "${REL_AG_EXTRA}" "test_ubo_extrasAG.txt"
          fi

      - name: Snapshot sources
        shell: bash
        env:
          NEED_MAIN: ${{ env.NEED_MAIN }}
          NEED_EXTRA: ${{ env.NEED_EXTRA }}
          DIFF_EXPIRES_MIN: ${{ env.DIFF_EXPIRES_MIN }}
        run: |
          set -e
          if [[ "${NEED_MAIN}" == "1" ]]; then
            cp "${SITE_DIR}/${OUT_UBO_MAIN}"  "${SITE_DIR}/${BASES_MAIN}/test-m-${{ steps.ts.outputs.epoch_min }}-${DIFF_EXPIRES_MIN}.base.txt"
          fi
          if [[ "${NEED_EXTRA}" == "1" ]]; then
            cp "${SITE_DIR}/${OUT_UBO_EXTRA}" "${SITE_DIR}/${BASES_EXTRA}/test-extra-m-${{ steps.ts.outputs.epoch_min }}-${DIFF_EXPIRES_MIN}.base.txt"
          fi

      - name: Regenerate patches (catch-up)
        shell: bash
        env:
          RETENTION_DAYS: ${{ env.RETENTION_DAYS }}
          DIFF_EXPIRES_MIN: ${{ env.DIFF_EXPIRES_MIN }}
          NEED_MAIN: ${{ env.NEED_MAIN }}
          NEED_EXTRA: ${{ env.NEED_EXTRA }}
        run: |
          set -euo pipefail
          NOW_EPOCH=${{ steps.ts.outputs.now_epoch }}
          RETENTION_SEC=$(( ${RETENTION_DAYS} * 24 * 3600 ))

          UBO_MAIN="${SITE_DIR}/${OUT_UBO_MAIN}"
          UBO_EXTRA="${SITE_DIR}/${OUT_UBO_EXTRA}"

          SHA1_UBO_MAIN=$( [[ -f "${UBO_MAIN}"  ]] && sha1sum "${UBO_MAIN}"  | awk '{print $1}' || echo "" )
          SHA1_UBO_EXTRA=$( [[ -f "${UBO_EXTRA}" ]] && sha1sum "${UBO_EXTRA}" | awk '{print $1}' || echo "" )

          write_bundle_pair() {
            local base_epoch="$1" content_file="$2" ag_name="$3"
            Y=$(date -u -d "@${base_epoch}" +%Y); Mo=$(date -u -d "@${base_epoch}" +%-m)
            D=$(date -u -d "@${base_epoch}" +%-d); H=$(date -u -d "@${base_epoch}" +%H)
            Mi=$(date -u -d "@${base_epoch}" +%M); MINS=$(( 10#${H}*60 + 10#${Mi} ))
            UBO="${Y}.${Mo}.${D}.${MINS}.patch"
            cat "${content_file}" > "${SITE_DIR}/${PATCH_DIR}/${UBO}"
            if [[ -n "$ag_name" ]]; then
              cat "${content_file}" > "${SITE_DIR}/${PATCH_DIR}/${ag_name}"
            fi
          }

          prune_for_epoch() {
            local base_epoch="$1" ag_name="$2"
            Y=$(date -u -d "@${base_epoch}" +%Y); Mo=$(date -u -d "@${base_epoch}" +%-m)
            D=$(date -u -d "@${base_epoch}" +%-d); H=$(date -u -d "@${base_epoch}" +%H)
            Mi=$(date -u -d "@${base_epoch}" +%M); MINS=$(( 10#${H}*60 + 10#${Mi} ))
            rm -f "${SITE_DIR}/${PATCH_DIR}/${Y}.${Mo}.${D}.${MINS}.patch"
            [[ -n "$ag_name" ]] && rm -f "${SITE_DIR}/${PATCH_DIR}/${ag_name}"
          }

          if [[ "${NEED_EXTRA}" == "1" ]]; then
            shopt -s nullglob
            for BF in "${SITE_DIR}/${BASES_MAIN}"/test-*-*.base.txt; do
              BN=$(basename "$BF")
              EPOCH_MIN=$(echo "$BN" | sed -n 's/^test-m-\([0-9]\+\)-[0-9]\+\.base\.txt$/\1/p') || true
              [[ -z "$EPOCH_MIN" ]] && { echo "Skip MAIN base: $BN"; continue; }
              BASE_EPOCH=$(( EPOCH_MIN * 60 ))
              AGE=$(( NOW_EPOCH - BASE_EPOCH ))
              if (( AGE > RETENTION_SEC )); then
                rm -f "$BF" "${SITE_DIR}/${BASES_EXTRA}/test-extra-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.base.txt"
                prune_for_epoch "$BASE_EPOCH" "testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
                prune_for_epoch "$BASE_EPOCH" "test_ubo_extrasAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
                continue
              fi

              diff -n "$BF" "${UBO_MAIN}" > raw_main.patch || true
              L_MAIN=$(wc -l < raw_main.patch | tr -d ' ')

              BF_EXTRA="${SITE_DIR}/${BASES_EXTRA}/test-extra-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.base.txt"
              if [[ -f "$BF_EXTRA" ]]; then
                diff -n "$BF_EXTRA" "${UBO_EXTRA}" > raw_extra.patch || true
              else
                : > raw_extra.patch
              fi
              L_EXTRA=$(wc -l < raw_extra.patch | tr -d ' ')

              {
                echo "diff name:test.txt checksum:${SHA1_UBO_MAIN} lines:${L_MAIN}"
                cat raw_main.patch
                echo "diff name:test_ubo_extras.txt checksum:${SHA1_UBO_EXTRA} lines:${L_EXTRA}"
                cat raw_extra.patch
              } > bundle.patch

              write_bundle_pair "$BASE_EPOCH" bundle.patch "testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
              cat bundle.patch > "${SITE_DIR}/${PATCH_DIR}/test_ubo_extrasAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
            done
            shopt -u nullglob
          fi

          if [[ "${NEED_MAIN}" == "1" && "${NEED_EXTRA}" == "0" ]]; then
            shopt -s nullglob
            for BF in "${SITE_DIR}/${BASES_MAIN}"/test-*-*.base.txt; do
              BN=$(basename "$BF")
              EPOCH_MIN=$(echo "$BN" | sed -n 's/^test-m-\([0-9]\+\)-[0-9]\+\.base\.txt$/\1/p') || true
              [[ -z "$EPOCH_MIN" ]] && { echo "Skip MAIN base: $BN"; continue; }
              BASE_EPOCH=$(( EPOCH_MIN * 60 ))
              AGE=$(( NOW_EPOCH - BASE_EPOCH ))
              if (( AGE > RETENTION_SEC )); then
                rm -f "$BF"
                prune_for_epoch "$BASE_EPOCH" "testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
                continue
              fi

              diff -n "$BF" "${UBO_MAIN}" > raw_main.patch || true
              L_MAIN=$(wc -l < raw_main.patch | tr -d ' ')
              {
                echo "diff name:test.txt checksum:${SHA1_UBO_MAIN} lines:${L_MAIN}"
                cat raw_main.patch
              } > bundle_main.patch

              write_bundle_pair "$BASE_EPOCH" bundle_main.patch "testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
            done
            shopt -u nullglob
          fi

      - name: Commit and push gh-pages
        working-directory: ${{ env.SITE_DIR }}
        shell: bash
        run: |
          set -e
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update modified filter lists"
            git push origin HEAD:gh-pages
          else
            echo "No changes to publish."
          fi
