      - name: Add Diff-Path (per output file)
        shell: bash
        run: |
          set -euo pipefail
          NOW_EPOCH=${{ steps.ts.outputs.now_epoch }}
          EPOCH_MIN=${{ steps.ts.outputs.epoch_min }}

          # uBO-heuristinen patchin nimi (sama kaikille uBO-julkaisuillle tässä ajossa)
          Y=$(date -u -d "@${NOW_EPOCH}" +%Y)
          Mo=$(date -u -d "@${NOW_EPOCH}" +%-m)
          D=$(date -u -d "@${NOW_EPOCH}" +%-d)
          H=$(date -u -d "@${NOW_EPOCH}" +%H)
          Mi=$(date -u -d "@${NOW_EPOCH}" +%M)
          MINS=$(( 10#${H}*60 + 10#${Mi} ))
          PATCH_UBO="${Y}.${Mo}.${D}.${MINS}.patch"
          REL_UBO="${PATCH_DIR}/${PATCH_UBO}"

          # AdGuard-patchien nimet per julkaisu
          PATCH_AG_MAIN="testAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
          REL_AG_MAIN="${PATCH_DIR}/${PATCH_AG_MAIN}"
          PATCH_AG_EXTRA="test_ubo_extrasAG-m-${EPOCH_MIN}-${DIFF_EXPIRES_MIN}.patch"
          REL_AG_EXTRA="${PATCH_DIR}/${PATCH_AG_EXTRA}"

          add_path () {
            local file="$1" rel="$2" frag="$3"
            local line="! Diff-Path: ${rel}#${frag}"
            # Poista olemassa olevat Diff-Path -rivit
            grep -vE '^! +Diff-Path:' "$file" > tmp && mv tmp "$file"
            # Lisää uusi Diff-Path heti Diff-Expires -rivin jälkeen (tai loppuun jos sitä ei ole)
            awk -v p="$line" '
              BEGIN{ins=0}
              {
                print
                if ($0 ~ /^! +Diff-Expires:/ && ins==0) { print p; ins=1 }
              }
              END { if (ins==0) print p }
            ' "$file" > tmp && mv tmp "$file"
          }

          if [[ "${NEED_MAIN}" == "1" ]]; then
            add_path "${SITE_DIR}/${OUT_UBO_MAIN}"  "${REL_UBO}"     "test.txt"
            add_path "${SITE_DIR}/${OUT_AG_MAIN}"   "${REL_AG_MAIN}" "testAG.txt"
          fi
          if [[ "${NEED_EXTRA}" == "1" ]]; then
            add_path "${SITE_DIR}/${OUT_UBO_EXTRA}" "${REL_UBO}"      "test_ubo_extras.txt"
            add_path "${SITE_DIR}/${OUT_AG_EXTRA}"  "${REL_AG_EXTRA}" "test_ubo_extrasAG.txt"
          fi
        env:
          NEED_MAIN:  ${{ env.NEED_MAIN }}
          NEED_EXTRA: ${{ env.NEED_EXTRA }}
          DIFF_EXPIRES_MIN: ${{ env.DIFF_EXPIRES_MIN }}
